name: Android CI Delivery Pipeline

on:
  push:
    branches: ["main"]

jobs:
  android-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Make Gradle executable
        run: chmod +x android/gradlew

      # ---------- BUILD APK ----------
      - name: Build Release APK
        run: |
          cd android
          ./gradlew assembleRelease

      # ---------- BUILD AAB ----------
      - name: Build Release AAB
        run: |
          cd android
          ./gradlew bundleRelease

      # ---------- UPLOAD ARTIFACTS ----------
      - name: Upload Release APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-apk
          path: android/app/build/outputs/apk/release/app-release.apk

      - name: Upload Release AAB Artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release-aab
          path: android/app/build/outputs/bundle/release/app-release.aab

      # ---------- FIREBASE AUTH ----------
      - name: Authenticate with Firebase (Service Account)
        run: |
          echo "${{ secrets.FIREBASE_SERVICE_ACCOUNT }}" | base64 --decode > service-account.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=$(pwd)/service-account.json" >> $GITHUB_ENV

      # ---------- INSTALL FIREBASE CLI ----------
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # ---------- UPLOAD APK ----------
      - name: Upload APK to Firebase App Distribution
        run: |
          firebase appdistribution:distribute \
          android/app/build/outputs/apk/release/app-release.apk \
          --app "${{ secrets.FIREBASE_APP_ID }}" \
          --testers "${{ secrets.FIREBASE_TESTERS }}"

      # Uncomment the following lines to enable AAB upload to Firebase App Distribution 
      # but it is requires atleast one build is uploaded to play console.

      # ---------- UPLOAD AAB ----------
      # - name: Upload AAB to Firebase App Distribution
      #   run: |
      #     firebase appdistribution:distribute \
      #     android/app/build/outputs/bundle/release/app-release.aab \
      #     --app "${{ secrets.FIREBASE_APP_ID }}" \
      #     --testers "${{ secrets.FIREBASE_TESTERS }}"